keys:
  - &atlas age1rrz6wef7gfymhnp30d46w2mfaldsztusklcezaj7g65qxxmqyyzqtt4ugc
  - &morpheus age1mhsrjvk37rvcmfuq06ccd2cl5wgevd2p0aftpncfv856jk0wcg7q9zz3nx
creation_rules:
  - path_regex: keys.yaml$
    key_groups:
      - age:
        - *atlas
        - *morpheus
