# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

	nixpkgs.hostPlatform = "x86_64-linux";

	disko.devices.disk.main.device = "/dev/sda";

	hardware.cpu.intel.updateMicrocode = config.hardware.enableRedistributableFirmware;

	boot = {
		lanzaboote.enable = false;

		initrd = {
			availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
			kernelModules = [ ];
		};
		kernelModules = [ "kvm-intel" ];
		extraModulePackages = [ ];
	};

	networking.hostId = "8425e349";
	environment.persistence."/persist".enable = true;

	# Did you read the Comment?
	# Change to your system.stateVersion
	system.stateVersion = "25.11";

}
